package managementasset

import (
	"os"
	"strings"

	log "github.com/sirupsen/logrus"
)

// patchManagementHTMLForCommandCode adds the provider to the existing workbench.
// All anchors must match before changing the bundle; unknown versions stay intact.
func patchManagementHTMLForCommandCode(input string) (string, bool) {
	if strings.Contains(input, "createCommandCodeConfig") {
		return input, true
	}
	if patched, ok := applyOpenCodeGoBundlePatches(input, commandCodeCurrentBundlePatches()); ok {
		return patched, true
	}
	return applyOpenCodeGoBundlePatches(input, commandCodeLegacyBundlePatches())
}

func commandCodeCurrentBundlePatches() []openCodeGoBundlePatch {
	return []openCodeGoBundlePatch{
		{old: "let openCodeGo=e[`opencode-go-api-key`];Array.isArray(openCodeGo)&&(t.openCodeGoKeys=openCodeGo.map(e=>openCodeGoParse(e)).filter(Boolean));", new: "let openCodeGo=e[`opencode-go-api-key`];Array.isArray(openCodeGo)&&(t.openCodeGoKeys=openCodeGo.map(e=>openCodeGoParse(e)).filter(Boolean));let commandCode=e[`command-code-api-key`];Array.isArray(commandCode)&&(t.commandCodeKeys=commandCode.map(e=>commandCodeParse(e)).filter(Boolean));", count: 1},
		{old: "case`opencode-go-api-key`:i.openCodeGoKeys=r;break;", new: "case`opencode-go-api-key`:i.openCodeGoKeys=r;break;case`command-code-api-key`:i.commandCodeKeys=r;break;", count: 1},
		{old: "openCodeGoFields=[`name`,`api-key`,`priority`,`prefix`,`base-url`,`proxy-url`,`headers`,`models`,`excluded-models`,`disable-cooling`],openCodeGoPayload=e=>{let t=Qv({...e,weight:void 0,websockets:void 0}),n=String(e?.name??``).trim();return delete t.weight,delete t.websockets,n&&(t.name=n),t},openCodeGoParse=e=>{let t=Bp(e);if(!t)return null;let n=String(e?.name??``).trim();n&&(t.name=n);let r=Number(e?.[`model-count`]);return Number.isFinite(r)&&(t.modelCount=r),t},", new: "openCodeGoFields=[`name`,`api-key`,`priority`,`prefix`,`base-url`,`proxy-url`,`headers`,`models`,`excluded-models`,`disable-cooling`],openCodeGoPayload=e=>{let t=Qv({...e,weight:void 0,websockets:void 0}),n=String(e?.name??``).trim();return delete t.weight,delete t.websockets,n&&(t.name=n),t},openCodeGoParse=e=>{let t=Bp(e);if(!t)return null;let n=String(e?.name??``).trim();n&&(t.name=n);let r=Number(e?.[`model-count`]);return Number.isFinite(r)&&(t.modelCount=r),t},commandCodeFields=[`name`,`api-key`,`priority`,`prefix`,`base-url`,`proxy-url`,`headers`,`models`,`excluded-models`,`disable-cooling`],commandCodePayload=e=>{let t=Qv({...e,weight:void 0,websockets:void 0}),n=String(e?.name??``).trim();return delete t.weight,delete t.websockets,n&&(t.name=n),t},commandCodeParse=e=>{let t=Bp(e);if(!t)return null;let n=String(e?.name??``).trim();n&&(t.name=n);let r=Number(e?.[`model-count`]);return Number.isFinite(r)&&(t.modelCount=r),t},", count: 1},
		{old: "async getOpenCodeGoConfigs(){return Jv(await Tp.get(`/opencode-go-api-key`),`opencode-go-api-key`).map(e=>openCodeGoParse(e)).filter(Boolean)},createOpenCodeGoConfig:e=>Hv(`opencode-go-api-key`,t=>Bv(t,openCodeGoPayload(e),(e,t)=>Kv(e,t,openCodeGoFields))),updateOpenCodeGoConfig:(e,t)=>Hv(`opencode-go-api-key`,n=>Vv(n,(t,n)=>n===e,openCodeGoPayload(t),(e,t)=>Kv(e,t,openCodeGoFields))),deleteOpenCodeGoConfig:e=>Tp.delete(`/opencode-go-api-key?index=${encodeURIComponent(String(e))}`),", new: "async getOpenCodeGoConfigs(){return Jv(await Tp.get(`/opencode-go-api-key`),`opencode-go-api-key`).map(e=>openCodeGoParse(e)).filter(Boolean)},createOpenCodeGoConfig:e=>Hv(`opencode-go-api-key`,t=>Bv(t,openCodeGoPayload(e),(e,t)=>Kv(e,t,openCodeGoFields))),updateOpenCodeGoConfig:(e,t)=>Hv(`opencode-go-api-key`,n=>Vv(n,(t,n)=>n===e,openCodeGoPayload(t),(e,t)=>Kv(e,t,openCodeGoFields))),deleteOpenCodeGoConfig:e=>Tp.delete(`/opencode-go-api-key?index=${encodeURIComponent(String(e))}`),async getCommandCodeConfigs(){return Jv(await Tp.get(`/command-code-api-key`),`command-code-api-key`).map(e=>commandCodeParse(e)).filter(Boolean)},createCommandCodeConfig:e=>Hv(`command-code-api-key`,t=>Bv(t,commandCodePayload(e),(e,t)=>Kv(e,t,commandCodeFields))),updateCommandCodeConfig:(e,t)=>Hv(`command-code-api-key`,n=>Vv(n,(t,n)=>n===e,commandCodePayload(t),(e,t)=>Kv(e,t,commandCodeFields))),deleteCommandCodeConfig:e=>Tp.delete(`/command-code-api-key?index=${encodeURIComponent(String(e))}`),", count: 1},
		{old: "opencodeGo:`OpenCode Go`,", new: "opencodeGo:`OpenCode Go`,commandCode:`Command Code`,", count: 3},
		{old: "opencodeGo:{id:`opencodeGo`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},", new: "opencodeGo:{id:`opencodeGo`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},commandCode:{id:`commandCode`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},", count: 1},
		{old: "jE=[`kimi`,`opencodeGo`,`gemini`", new: "jE=[`kimi`,`opencodeGo`,`commandCode`,`gemini`", count: 1},
		{old: "e===`opencodeGo`?`https://opencode.ai/zen/go/v1`:", new: "e===`opencodeGo`?`https://opencode.ai/zen/go/v1`:e===`commandCode`?`https://api.commandcode.ai`:", count: 1},
		{old: "return{apiKey:``,name:e===`opencodeGo`?i.name??``:``,baseUrl:i.baseUrl??``", new: "return{apiKey:``,name:(e===`opencodeGo`||e===`commandCode`)?i.name??``:``,baseUrl:i.baseUrl??``", count: 1},
		{old: "o={name:e===`opencodeGo`?t.name.trim()||void 0:void 0,apiKey:t.apiKey.trim().length>0?t.apiKey.trim():n?.apiKey??``,priority:", new: "o={name:(e===`opencodeGo`||e===`commandCode`)?t.name.trim()||void 0:void 0,apiKey:t.apiKey.trim().length>0?t.apiKey.trim():n?.apiKey??``,priority:", count: 1},
		{old: "if(c.supportsName&&e!==`opencodeGo`&&!u.name.trim())return s(`providersPage.form.validation.nameRequired`);", new: "if(c.supportsName&&e!==`opencodeGo`&&e!==`commandCode`&&!u.name.trim())return s(`providersPage.form.validation.nameRequired`);", count: 1},
		{old: "function openCodeGoResource(e,t){let n=(e.name??``).trim(),r=AD(`opencodeGo`,e,t);return{...r,name:n||null,identifier:n||Xh(e.apiKey)||`OpenCode Go #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}", new: "function openCodeGoResource(e,t){let n=(e.name??``).trim(),r=AD(`opencodeGo`,e,t);return{...r,name:n||null,identifier:n||Xh(e.apiKey)||`OpenCode Go #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}function commandCodeResource(e,t){let n=(e.name??``).trim(),r=AD(`commandCode`,e,t);return{...r,name:n||null,identifier:n||Xh(e.apiKey)||`Command Code #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}", count: 1},
		{old: "let[e,t,i,openCodeGo]=await Promise.allSettled([n(!0),ry.getVertexConfigs(),ry.getOpenAIProviders(),ry.getOpenCodeGoConfigs()]);if(e.status!==`fulfilled`)throw e.reason;t.status===`fulfilled`&&r(`vertex-api-key`,t.value||[]),i.status===`fulfilled`&&r(`openai-compatibility`,i.value||[]),openCodeGo.status===`fulfilled`&&r(`opencode-go-api-key`,openCodeGo.value||[]),m(new Date().toISOString())", new: "let[e,t,i,openCodeGo,commandCode]=await Promise.allSettled([n(!0),ry.getVertexConfigs(),ry.getOpenAIProviders(),ry.getOpenCodeGoConfigs(),ry.getCommandCodeConfigs()]);if(e.status!==`fulfilled`)throw e.reason;t.status===`fulfilled`&&r(`vertex-api-key`,t.value||[]),i.status===`fulfilled`&&r(`openai-compatibility`,i.value||[]),openCodeGo.status===`fulfilled`&&r(`opencode-go-api-key`,openCodeGo.value||[]),commandCode.status===`fulfilled`&&r(`command-code-api-key`,commandCode.value||[]),m(new Date().toISOString())", count: 1},
		{old: "case`opencodeGo`:i=(t.openCodeGoKeys??[]).map((e,t)=>openCodeGoResource(e,t));break;", new: "case`opencodeGo`:i=(t.openCodeGoKeys??[]).map((e,t)=>openCodeGoResource(e,t));break;case`commandCode`:i=(t.commandCodeKeys??[]).map((e,t)=>commandCodeResource(e,t));break;", count: 1},
		{old: "e===`opencodeGo`?await ry.createOpenCodeGoConfig(QD(`opencodeGo`,t)):", new: "e===`opencodeGo`?await ry.createOpenCodeGoConfig(QD(`opencodeGo`,t)):e===`commandCode`?await ry.createCommandCodeConfig(QD(`commandCode`,t)):", count: 1},
		{old: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw;await ry.updateOpenCodeGoConfig(r.index,QD(`opencodeGo`,t,n))}", new: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw;await ry.updateOpenCodeGoConfig(r.index,QD(`opencodeGo`,t,n))}else if(n===`commandCode`&&r.brand===`commandCode`){let n=e.raw;await ry.updateCommandCodeConfig(r.index,QD(`commandCode`,t,n))}", count: 1},
		{old: "else if(n.brand===`opencodeGo`){await ry.deleteOpenCodeGoConfig(n.index);let e=(t?.openCodeGoKeys??[]).filter((e,t)=>t!==n.index);r(`opencode-go-api-key`,e)}", new: "else if(n.brand===`opencodeGo`){await ry.deleteOpenCodeGoConfig(n.index);let e=(t?.openCodeGoKeys??[]).filter((e,t)=>t!==n.index);r(`opencode-go-api-key`,e)}else if(n.brand===`commandCode`){await ry.deleteCommandCodeConfig(n.index);let e=(t?.commandCodeKeys??[]).filter((e,t)=>t!==n.index);r(`command-code-api-key`,e)}", count: 1},
		{old: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw,i=t?Ax(n.excludedModels):jx(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await Tp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await ry.updateOpenCodeGoConfig(r.index,a)}", new: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw,i=t?Ax(n.excludedModels):jx(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await Tp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await ry.updateOpenCodeGoConfig(r.index,a)}else if(n===`commandCode`&&r.brand===`commandCode`){let n=e.raw,i=t?Ax(n.excludedModels):jx(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await Tp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await ry.updateCommandCodeConfig(r.index,a)}", count: 1},
		{old: "opencodeGo:e.openCodeGoKeys?.length??0,", new: "opencodeGo:e.openCodeGoKeys?.length??0,commandCode:e.commandCodeKeys?.length??0,", count: 1},
		{old: "if(e.brand===`opencodeGo`)return", new: "if(e.brand===`opencodeGo`||e.brand===`commandCode`)return", count: 1},
	}
}

func EnsureCommandCodeOnDisk(path string) {
	data, err := os.ReadFile(path)
	if err != nil {
		return
	}
	patched, ok := patchManagementHTMLForCommandCode(string(data))
	if !ok {
		log.Debug("command-code panel skipped: unsupported bundle")
		return
	}
	if patched == string(data) {
		return
	}
	if err = atomicWriteFile(path, []byte(patched)); err != nil {
		log.WithError(err).Warn("command-code panel write failed")
	}
}

func commandCodeLegacyBundlePatches() []openCodeGoBundlePatch {
	return []openCodeGoBundlePatch{
		{old: "let opencodeGo=e[`opencode-go-api-key`];Array.isArray(opencodeGo)&&(t.openCodeGoKeys=opencodeGo.map(e=>vp(e)).filter(Boolean));", new: "let opencodeGo=e[`opencode-go-api-key`];Array.isArray(opencodeGo)&&(t.openCodeGoKeys=opencodeGo.map(e=>vp(e)).filter(Boolean));let commandCode=e[`command-code-api-key`];Array.isArray(commandCode)&&(t.commandCodeKeys=commandCode.map(e=>vp(e)).filter(Boolean));", count: 1},
		{old: "case`opencode-go-api-key`:i.openCodeGoKeys=r;break;", new: "case`opencode-go-api-key`:i.openCodeGoKeys=r;break;case`command-code-api-key`:i.commandCodeKeys=r;break;", count: 1},
		{old: "async getOpenCodeGoConfigs(){return fv(await sp.get(`/opencode-go-api-key`),`opencode-go-api-key`).map(e=>vp(e)).filter(Boolean)},createOpenCodeGoConfig:e=>ov(`opencode-go-api-key`,t=>iv(t,gv(e),(e,t)=>uv(e,t,R_))),updateOpenCodeGoConfig:(e,t)=>ov(`opencode-go-api-key`,n=>av(n,(t,n)=>n===e,gv(t),(e,t)=>uv(e,t,R_))),deleteOpenCodeGoConfig:e=>sp.delete(`/opencode-go-api-key?index=${encodeURIComponent(String(e))}`),", new: "async getOpenCodeGoConfigs(){return fv(await sp.get(`/opencode-go-api-key`),`opencode-go-api-key`).map(e=>vp(e)).filter(Boolean)},createOpenCodeGoConfig:e=>ov(`opencode-go-api-key`,t=>iv(t,gv(e),(e,t)=>uv(e,t,R_))),updateOpenCodeGoConfig:(e,t)=>ov(`opencode-go-api-key`,n=>av(n,(t,n)=>n===e,gv(t),(e,t)=>uv(e,t,R_))),deleteOpenCodeGoConfig:e=>sp.delete(`/opencode-go-api-key?index=${encodeURIComponent(String(e))}`),async getCommandCodeConfigs(){return fv(await sp.get(`/command-code-api-key`),`command-code-api-key`).map(e=>vp(e)).filter(Boolean)},createCommandCodeConfig:e=>ov(`command-code-api-key`,t=>iv(t,gv(e),(e,t)=>uv(e,t,R_))),updateCommandCodeConfig:(e,t)=>ov(`command-code-api-key`,n=>av(n,(t,n)=>n===e,gv(t),(e,t)=>uv(e,t,R_))),deleteCommandCodeConfig:e=>sp.delete(`/command-code-api-key?index=${encodeURIComponent(String(e))}`),", count: 1},
		{old: "opencodeGo:`OpenCode Go`,", new: "opencodeGo:`OpenCode Go`,commandCode:`Command Code`,", count: 3},
		{old: "opencodeGo:{id:`opencodeGo`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},", new: "opencodeGo:{id:`opencodeGo`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},commandCode:{id:`commandCode`,supportsName:!0,supportsApiKey:!0,supportsDisabled:!0,supportsBaseUrl:!0,baseUrlRequired:!1,supportsProxyUrl:!0,supportsPrefix:!0,supportsModels:!0,supportsHeaders:!0,supportsExcludedModels:!0,supportsPriority:!0,supportsTestModel:!1,supportsWebsockets:!1,supportsCloak:!1,supportsApiKeyEntries:!1,sheetSize:`md`},", count: 1},
		{old: "eT=[`kimi`,`opencodeGo`,`gemini`", new: "eT=[`kimi`,`opencodeGo`,`commandCode`,`gemini`", count: 1},
		{old: "e===`opencodeGo`?`https://opencode.ai/zen/go/v1`:", new: "e===`opencodeGo`?`https://opencode.ai/zen/go/v1`:e===`commandCode`?`https://api.commandcode.ai`:", count: 1},
		{old: "return{apiKey:``,name:e===`opencodeGo`?i.name??``:``,baseUrl:i.baseUrl??``", new: "return{apiKey:``,name:(e===`opencodeGo`||e===`commandCode`)?i.name??``:``,baseUrl:i.baseUrl??``", count: 1},
		{old: "o={name:e===`opencodeGo`?t.name.trim()||void 0:void 0,apiKey:t.apiKey.trim().length>0?t.apiKey.trim():n?.apiKey??``,priority:", new: "o={name:(e===`opencodeGo`||e===`commandCode`)?t.name.trim()||void 0:void 0,apiKey:t.apiKey.trim().length>0?t.apiKey.trim():n?.apiKey??``,priority:", count: 1},
		{old: "c.supportsName&&e!==`opencodeGo`&&!u.name.trim()?s(`providersPage.form.validation.nameRequired`)", new: "c.supportsName&&e!==`opencodeGo`&&e!==`commandCode`&&!u.name.trim()?s(`providersPage.form.validation.nameRequired`)", count: 1},
		{old: "function openCodeGoResource(e,t){let n=(e.name??``).trim(),r=MT(`opencodeGo`,e,t);return{...r,name:n||null,identifier:n||Mh(e.apiKey)||`OpenCode Go #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}", new: "function openCodeGoResource(e,t){let n=(e.name??``).trim(),r=MT(`opencodeGo`,e,t);return{...r,name:n||null,identifier:n||Mh(e.apiKey)||`OpenCode Go #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}function commandCodeResource(e,t){let n=(e.name??``).trim(),r=MT(`commandCode`,e,t);return{...r,name:n||null,identifier:n||Mh(e.apiKey)||`Command Code #${t+1}`,modelCount:e.modelCount??e.models?.length??0}}", count: 1},
		{old: "let[e,t,i,opencodeGo]=await Promise.allSettled([n(!0),xv.getVertexConfigs(),xv.getOpenAIProviders(),xv.getOpenCodeGoConfigs()]);if(e.status!==`fulfilled`)throw e.reason;t.status===`fulfilled`&&r(`vertex-api-key`,t.value||[]),i.status===`fulfilled`&&r(`openai-compatibility`,i.value||[]),opencodeGo.status===`fulfilled`&&r(`opencode-go-api-key`,opencodeGo.value||[]),m(new Date().toISOString())", new: "let[e,t,i,opencodeGo,commandCode]=await Promise.allSettled([n(!0),xv.getVertexConfigs(),xv.getOpenAIProviders(),xv.getOpenCodeGoConfigs(),xv.getCommandCodeConfigs()]);if(e.status!==`fulfilled`)throw e.reason;t.status===`fulfilled`&&r(`vertex-api-key`,t.value||[]),i.status===`fulfilled`&&r(`openai-compatibility`,i.value||[]),opencodeGo.status===`fulfilled`&&r(`opencode-go-api-key`,opencodeGo.value||[]),commandCode.status===`fulfilled`&&r(`command-code-api-key`,commandCode.value||[]),m(new Date().toISOString())", count: 1},
		{old: "case`opencodeGo`:n=(t.openCodeGoKeys??[]).map((e,t)=>openCodeGoResource(e,t));break;", new: "case`opencodeGo`:n=(t.openCodeGoKeys??[]).map((e,t)=>openCodeGoResource(e,t));break;case`commandCode`:n=(t.commandCodeKeys??[]).map((e,t)=>commandCodeResource(e,t));break;", count: 1},
		{old: "e===`opencodeGo`?await xv.createOpenCodeGoConfig(ZT(`opencodeGo`,t)):", new: "e===`opencodeGo`?await xv.createOpenCodeGoConfig(ZT(`opencodeGo`,t)):e===`commandCode`?await xv.createCommandCodeConfig(ZT(`commandCode`,t)):", count: 1},
		{old: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw;await xv.updateOpenCodeGoConfig(r.index,ZT(`opencodeGo`,t,n))}", new: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw;await xv.updateOpenCodeGoConfig(r.index,ZT(`opencodeGo`,t,n))}else if(n===`commandCode`&&r.brand===`commandCode`){let n=e.raw;await xv.updateCommandCodeConfig(r.index,ZT(`commandCode`,t,n))}", count: 1},
		{old: "else if(n.brand===`opencodeGo`){await xv.deleteOpenCodeGoConfig(n.index);let e=(t?.openCodeGoKeys??[]).filter((e,t)=>t!==n.index);r(`opencode-go-api-key`,e)}", new: "else if(n.brand===`opencodeGo`){await xv.deleteOpenCodeGoConfig(n.index);let e=(t?.openCodeGoKeys??[]).filter((e,t)=>t!==n.index);r(`opencode-go-api-key`,e)}else if(n.brand===`commandCode`){await xv.deleteCommandCodeConfig(n.index);let e=(t?.commandCodeKeys??[]).filter((e,t)=>t!==n.index);r(`command-code-api-key`,e)}", count: 1},
		{old: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw,i=t?Jb(n.excludedModels):Yb(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await sp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await xv.updateOpenCodeGoConfig(r.index,a)}", new: "else if(n===`opencodeGo`&&r.brand===`opencodeGo`){let n=e.raw,i=t?Jb(n.excludedModels):Yb(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await sp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await xv.updateOpenCodeGoConfig(r.index,a)}else if(n===`commandCode`&&r.brand===`commandCode`){let n=e.raw,i=t?Jb(n.excludedModels):Yb(n.excludedModels),a={...n,excludedModels:i};e.authIndex?await sp.patch(`/auth-files/status`,{name:e.authIndex,disabled:t}):await xv.updateCommandCodeConfig(r.index,a)}", count: 1},
		{old: "opencodeGo:n.openCodeGoKeys?.length??0,", new: "opencodeGo:n.openCodeGoKeys?.length??0,commandCode:n.commandCodeKeys?.length??0,", count: 1},
		{old: "if(e.brand===`opencodeGo`)return", new: "if(e.brand===`opencodeGo`||e.brand===`commandCode`)return", count: 1},
	}
}
